project_id = "dlirkqmsjnlwbsfzzfjb"

[functions.send-auth-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.test-api-connections]
verify_jwt = false

[functions.stocks-api]
verify_jwt = false

[functions.stock-analysis]
verify_jwt = false

[functions.fetch-stock-news]
verify_jwt = false